// react/app/components/ui/App/App.tsx
import {Navbar} from "@/components/ui/Navbar"

export function App({children}) {

    const style = { "min_width": "var(--breakpoint-xs)" } as React.CSSProperties;

    return (
        <div className="text-center">
            <div className="overflow-auto w-full h-screen" style={style}>
                <Navbar/>
                {children}
            </div>
        </div>
    )
}

// svelte/src/lib/components/app/app.svelte
<script lang="ts">
	let { children } = $props();
    import Navbar from "$lib/components/app/navbar.svelte";
</script>

<div style="text-align: center">
    <!--  style="min-width: var(--breakpoint-xs); max-width: var(--breakpoint-lg)" -->
      <!-- inline-grid -->
    <div class="overflow-auto w-full h-screen"  style="min-width: var(--breakpoint-xs)">
        <Navbar/>
        {@render children()}
    </div>
</div>
